apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi-nas
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
mountOptions:
  - hard
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
allowVolumeExpansion: True
reclaimPolicy: Delete